---
title: "Final Project"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#use_python()
```

## R Markdown

```{r}
#install.packages("arules")
#install.packages("ggplot2")

library(arules)
library(ggplot2)

data <- read.csv(file = "AppleStoreClean.csv", head = TRUE)
tdata <- read.transactions("AppleStoreClean.csv", quote="", sep=",")
cutdata <- read.transactions("AppleStoreCut.csv", quote="", sep=",")
modified_data <- data
```

## HCLUST

```{r}
distance = dist(as.matrix(data), method = "euclidean")

# perform clustering
hc = hclust(distance)

# cut the tree
clusterCut <- cutree(hc, 300)

# plot dendrogram
plot(clusterCut)

#write.csv(clusterCut, file = =hclust.csv")
```

## Apriori - Regular

```{r}
apprules <- apriori(tdata, parameter = list(support = 0.03, confidence = 0.35, minlen = 2))

summary(apprules)

inspect(sort(apprules, by = "lift")[1:20])

#itemFrequencyPlot(tdata, support = 0.1) # items with a support of 0.1
#itemFrequencyPlot(tdata, topN = 20) # 20 most frequent items
```

## Apriori - Cut Data

```{r}
cutrules <- apriori(cutdata, parameter = list(support = 0.03, confidence = 0.35, minlen = 2))

summary(cutrules)

inspect(sort(cutrules, by = "lift")[1:20])

#itemFrequencyPlot(tdata, support = 0.1) # items with a support of 0.1
#itemFrequencyPlot(tdata, topN = 20) # 20 most frequent items
```

## cut data/label encoding

```{r}
data_cut <- data[, c(3, 4, 6, 8, 9)]

data2 <- read.csv(file = "AppleStoreEncoded.csv", head = TRUE)
data_encoded <- data2[, c(3, 4, 6, 8, 9)]
data_encoded <- scale(data_encoded)

#for(i in 1:length(data_cut$prime_genre)) {
#  if(data_cut$prime_genre[i] == "Games") data_cut$prime_genre[i] <- 1
#}


```

## Optimal K

```{r}

k.max <- 15
wss <- sapply(1:k.max, 
              function(k){kmeans(data_encoded, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

```

## kmeans

```{r}
# Cluster into k=5 clusters:
myClusters = kmeans(data_encoded, 3)

# Summary of the clusters
summary(myClusters)

# Centers (mean values) of the clusters
myClusters$centers

# Cluster assignments
myClusters$cluster

# Within-cluster sum of squares and total sum of squares across clusters
myClusters$withinss
myClusters$tot.withinss


# Plotting a visual representation of k-means clusters
library(cluster)
clusplot(data_encoded, myClusters$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)

```
```{r}
for (i in 1:25) {
  myClusters = kmeans(data_encoded, i)
  print(myClusters$tot.withinss)
}
```

## optimal k

```{r}

k.max <- 15
wss <- sapply(1:k.max, 
              function(k){kmeans(data_encoded, k, nstart=50,iter.max = 15 )$tot.withinss})
wss
plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

```

## New column based on cost

```{r}
modified_data$isFree <- (data$price == 0)
split_data <- split(modified_data, modified_data$isFree)
free_data <- data.frame(split_data[2])
cost_data <- data.frame(split_data[1])
```

## GG PLOT GRAPHS

## Pie Chart

```{r}
bp <- ggplot(data, aes(x="", y="", fill=prime_genre)) + geom_bar(stat="identity")
pie <- bp + coord_polar("y", start=0)
pie
```


## Genre graphs

```{r}
# All Apps
all_bar <- ggplot(data, aes(prime_genre, fill = prime_genre)) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar() + ggtitle("All App Genres") + xlab("genre") + ylab("count")
all_bar

# Free Apps
ggplot(free_data, aes(TRUE.prime_genre, fill = TRUE.prime_genre)) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar() + ggtitle("Free App Genres") + xlab("genre") + ylab("count")

# Paid Apps
ggplot(cost_data, aes(FALSE.prime_genre, fill = FALSE.prime_genre)) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar() + ggtitle("Paid App Genres") + xlab("genre") + ylab("count")

# Both
both_bar <- ggplot(modified_data, aes(x = prime_genre, fill = isFree)) + theme(axis.text.x = element_text(angle = 90, hjust = 1))+ geom_bar(position="dodge") + ggtitle("Free vs Paid App Genres") + xlab("genre") + ylab("count")
both_bar
```

## Rating vs genre

```{r}
ggplot(data) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar(aes(x = prime_genre, y= user_rating, fill = prime_genre), stat = "summary", fun.y = "mean") + ggtitle("Average User Rating by Genre") + xlab("genre") + ylab("average user rating")

ggplot(data) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar(aes(x = prime_genre, y= size_bytes, fill = prime_genre), stat = "summary", fun.y = "mean") + ggtitle("Average Size (bytes) by Genre") + xlab("genre") + ylab("average size (bytes)")

ggplot(data) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + geom_bar(aes(x = prime_genre, y= price, fill = prime_genre), stat = "summary", fun.y = "mean") + ggtitle("Average Price by Genre") + xlab("genre") + ylab("average price")
```





## USELESS ONCE THE GG PLOT GRAPHS ARE FUNCTIONING

## Bar Graph - Genres

```{r}
tbl <- with(data, table(prime_genre))
barplot(tbl, beside = TRUE, legend = FALSE, main = "Application Genres", xlab = "genre", ylab = "number")

tbl <- with(free_data, table(TRUE.prime_genre))
barplot(tbl, beside = TRUE, legend = FALSE, main = "Free App Genres", xlab = "genre", ylab = "number")

tbl <- with(cost_data, table(FALSE.prime_genre))
barplot(tbl, beside = TRUE, legend = FALSE, main = "Paid App Genres", xlab = "genre", ylab = "number")
```
